# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  check_dawn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "shopify/dawn"
          path: "./dawn"

      - name: Lighthouse CI action
        uses: ./
        id: lighthouse-ci-action
        with:
          app_id: ${{ secrets.SHOP_APP_ID }}
          app_password: ${{ secrets.SHOP_APP_PASSWORD }}
          store: shimmering-islands.myshopify.com
          theme_root: "./dawn"
          lhci_min_score_performance: 0.1
          lhci_min_score_accessibility: 0.1
